insert into product_type (id, name) values (1, 'Top products');
insert into product_type (id, name) values (2, 'New products');
insert into product_type (id, name) values (3, 'Sale products');

insert into product (id, name, new_product, hot_product, price, old_price, image, description, product_type_id) values (1, 'Product1', true, false, 123.56, 150.00, 's1.jpg', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque leo ante, dictum quis commodo ut, molestie vitae sapien. Vestibulum sagittis velit sollicitudin lacus blandit ullamcorper. Fusce a lorem sed augue dignissim dignissim ac id enim. Etiam a posuere mauris. Mauris vitae vulputate augue. In vitae ex eu odio dapibus scelerisque.', 1);
insert into product (id, name, new_product, hot_product, price, old_price, image, description, product_type_id) values (2, 'Product2', false, true, 123.56, 150.00, 's2.jpg', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque leo ante, dictum quis commodo ut, molestie vitae sapien. Vestibulum sagittis velit sollicitudin lacus blandit ullamcorper. Fusce a lorem sed augue dignissim dignissim ac id enim. Etiam a posuere mauris. Mauris vitae vulputate augue. In vitae ex eu odio dapibus scelerisque.', 1);
insert into product (id, name, new_product, hot_product, price, old_price, image, description, product_type_id) values (3, 'Product3', false, false, 123.56, 150.00, 's3.jpg', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque leo ante, dictum quis commodo ut, molestie vitae sapien. Vestibulum sagittis velit sollicitudin lacus blandit ullamcorper. Fusce a lorem sed augue dignissim dignissim ac id enim. Etiam a posuere mauris. Mauris vitae vulputate augue. In vitae ex eu odio dapibus scelerisque.', 1);
insert into product (id, name, new_product, hot_product, price, old_price, image, description, product_type_id) values (4, 'Product4', false, false, 123.56, 150.00, 's4.jpg', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque leo ante, dictum quis commodo ut, molestie vitae sapien. Vestibulum sagittis velit sollicitudin lacus blandit ullamcorper. Fusce a lorem sed augue dignissim dignissim ac id enim. Etiam a posuere mauris. Mauris vitae vulputate augue. In vitae ex eu odio dapibus scelerisque.', 1);
insert into product (id, name, new_product, hot_product, price, old_price, image, description, product_type_id) values (5, 'Product5', false, false, 123.56, 150.00, 's5.jpg', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque leo ante, dictum quis commodo ut, molestie vitae sapien. Vestibulum sagittis velit sollicitudin lacus blandit ullamcorper. Fusce a lorem sed augue dignissim dignissim ac id enim. Etiam a posuere mauris. Mauris vitae vulputate augue. In vitae ex eu odio dapibus scelerisque.', 1);

insert into product (id, name, new_product, hot_product, price, old_price, image, description, product_type_id) values (6, 'Product1', true, false, 123.56, 150.00, 's6.jpg', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque leo ante, dictum quis commodo ut, molestie vitae sapien. Vestibulum sagittis velit sollicitudin lacus blandit ullamcorper. Fusce a lorem sed augue dignissim dignissim ac id enim. Etiam a posuere mauris. Mauris vitae vulputate augue. In vitae ex eu odio dapibus scelerisque.', 2);
insert into product (id, name, new_product, hot_product, price, old_price, image, description, product_type_id) values (7, 'Product2', false, true, 123.56, 150.00, 's7.jpg', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque leo ante, dictum quis commodo ut, molestie vitae sapien. Vestibulum sagittis velit sollicitudin lacus blandit ullamcorper. Fusce a lorem sed augue dignissim dignissim ac id enim. Etiam a posuere mauris. Mauris vitae vulputate augue. In vitae ex eu odio dapibus scelerisque.', 2);
insert into product (id, name, new_product, hot_product, price, old_price, image, description, product_type_id) values (8, 'Product3', false, false, 123.56, 150.00, 's8.jpg', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque leo ante, dictum quis commodo ut, molestie vitae sapien. Vestibulum sagittis velit sollicitudin lacus blandit ullamcorper. Fusce a lorem sed augue dignissim dignissim ac id enim. Etiam a posuere mauris. Mauris vitae vulputate augue. In vitae ex eu odio dapibus scelerisque.', 2);
insert into product (id, name, new_product, hot_product, price, old_price, image, description, product_type_id) values (9, 'Product4', false, false, 123.56, 150.00, 's9.jpg', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque leo ante, dictum quis commodo ut, molestie vitae sapien. Vestibulum sagittis velit sollicitudin lacus blandit ullamcorper. Fusce a lorem sed augue dignissim dignissim ac id enim. Etiam a posuere mauris. Mauris vitae vulputate augue. In vitae ex eu odio dapibus scelerisque.', 2);
insert into product (id, name, new_product, hot_product, price, old_price, image, description, product_type_id) values (10, 'Product5', false, false, 123.56, 150.00, 's10.jpg', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque leo ante, dictum quis commodo ut, molestie vitae sapien. Vestibulum sagittis velit sollicitudin lacus blandit ullamcorper. Fusce a lorem sed augue dignissim dignissim ac id enim. Etiam a posuere mauris. Mauris vitae vulputate augue. In vitae ex eu odio dapibus scelerisque.', 2);

insert into product (id, name, new_product, hot_product, price, old_price, image, description, product_type_id) values (11, 'Product1', true, false, 123.56, 150.00, 's11.jpg', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque leo ante, dictum quis commodo ut, molestie vitae sapien. Vestibulum sagittis velit sollicitudin lacus blandit ullamcorper. Fusce a lorem sed augue dignissim dignissim ac id enim. Etiam a posuere mauris. Mauris vitae vulputate augue. In vitae ex eu odio dapibus scelerisque.', 3);
insert into product (id, name, new_product, hot_product, price, old_price, image, description, product_type_id) values (12, 'Product2', false, true, 123.56, 150.00, 's12.jpg', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque leo ante, dictum quis commodo ut, molestie vitae sapien. Vestibulum sagittis velit sollicitudin lacus blandit ullamcorper. Fusce a lorem sed augue dignissim dignissim ac id enim. Etiam a posuere mauris. Mauris vitae vulputate augue. In vitae ex eu odio dapibus scelerisque.', 3);
insert into product (id, name, new_product, hot_product, price, old_price, image, description, product_type_id) values (13, 'Product3', false, false, 123.56, 150.00, 's1.jpg', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque leo ante, dictum quis commodo ut, molestie vitae sapien. Vestibulum sagittis velit sollicitudin lacus blandit ullamcorper. Fusce a lorem sed augue dignissim dignissim ac id enim. Etiam a posuere mauris. Mauris vitae vulputate augue. In vitae ex eu odio dapibus scelerisque.', 3);
insert into product (id, name, new_product, hot_product, price, old_price, image, description, product_type_id) values (14, 'Product4', false, false, 123.56, 150.00, 's2.jpg', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque leo ante, dictum quis commodo ut, molestie vitae sapien. Vestibulum sagittis velit sollicitudin lacus blandit ullamcorper. Fusce a lorem sed augue dignissim dignissim ac id enim. Etiam a posuere mauris. Mauris vitae vulputate augue. In vitae ex eu odio dapibus scelerisque.', 3);
insert into product (id, name, new_product, hot_product, price, old_price, image, description, product_type_id) values (15, 'Product5', false, false, 123.56, 150.00, 's3.jpg', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque leo ante, dictum quis commodo ut, molestie vitae sapien. Vestibulum sagittis velit sollicitudin lacus blandit ullamcorper. Fusce a lorem sed augue dignissim dignissim ac id enim. Etiam a posuere mauris. Mauris vitae vulputate augue. In vitae ex eu odio dapibus scelerisque.', 3);